<?php

/*  DAlbum English-US language support file

    (c) Copyright 2003 by DeltaX Inc.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'          => 'Log in',
    'loginBtnTitle'     => 'Log in',

    'logoutBtn'         => 'Log out',
    'logoutBtnTitle'    => 'Log out',

    'reindexBtn'        => 'Reindex',
    'reindexBtnTitle'   => 'Search for new images and update DAlbum database',

    'usrmgrBtn'         => 'Users',
    'usrmgrBtnTitle'    => 'Add/remove users and change passwords',

    'closeWindowBtn'    => 'Close window',
    'closeWindowBtnTitle'=> 'Close this window',

    'fullScreenBtn'         => 'Full screen',
    'fullScreenBtnTitle'    => 'Open this page in a full-screen window. Or just press F11 to the same effect',

    'editDefBtn'            => 'Edit',
    'editDefBtnTitle'       => 'Edit album title, comments and manage album images',

    'indexUsername'         => 'User:',
    'page'                  => 'Displaying items #begin# - #end# of #count#. &nbsp; Page: &nbsp;',
    'noimages'              => 'No images',
    'noPublicImages'        => 'No public images available. Please log in.',
    'noscript'              => 'Sorry, folder view can only be displayed with Javascript support turned on in your browser.<BR><BR>Please go to your browser preferences and enable Javascript for this site.',

    'prevPageBtn'           => 'Previous',
    'prevPageBtnTitle'      => 'Go to the previous page (#page#)',

    'nextPageBtn'           => 'Next',
    'nextPageBtnTitle'      => 'Go to the next page (#page#)',

    'allPageBtn'           => 'All',
    'allPageBtnTitle'      => 'Show all pages',

    'statusLeft'            => '<b>#TotalImages#</b> images in <b>#TotalAlbums#</b> albums',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'              => 'Go to main page',
    'username'              => 'Username:',
    'password'              => 'Password:',
    'bytes'                 => 'bytes',
    'KB'                    => 'KB',
    'MB'                    => 'MB',
    'pixels'                => 'pixels',
    'errorReturn'           => 'Return to the previous page',

    /// Login.php
    'loginTitle'            =>  'Login to #title#',
    'loginAuthError'        =>  'Authentication error',
    'loginBadUserName'      =>  'Your username or password were not found in the database.',
    'loginAgain'            =>  'Login again',
    'loginNoCookiesWarning' =>  '<HR><B>Warning: Cookies are disabled in your browser!</B><BR>In order to continue cookies must be enabled.<BR>Please enable cookies in your browser preferences and refresh this page.<BR><HR>',
    'loginLoginBtn'         => 'Login',
    'loginCancelBtn'        => 'Cancel',

    // pass.php
    'passTitle'             => 'User manager',
    'passUserExists'        => 'User #user# already exists.',
    'passNotMatch'          => 'Passwords do not match.',
    'passNoUserSelected'    => 'No user selected.',
    'passNoAdminDelete'     => 'Primary DAlbum administrator cannot be deleted.',
    'passWriteError'        => 'Unable to open password file for writing!',
    'passError'             => '<B>Error: </B>#error#',
    'passAddBtn'            => 'Add',
    'passDeleteBtn'         => 'Delete',
    'passChangePwdBtn'      => 'Change password',
    'passCloseBtn'          => 'Close',
    'passCancelBtn'         => 'Cancel',

    'passAddUserDlgTitle'   => 'Add user',
    'passChangePwdDlgTitle' => 'Change password',
    'passConfirmPassword'   => 'Confirm password:',

    // showimg.php
    'showPrevBtn'           => 'Previous',
    'showPrevBtnTitle'      => 'Show previous image',

    'showNextBtn'           => 'Next',
    'showNextBtnTitle'      => 'Show next image',

    'showIndexBtn'          => 'Index',
    'showIndexBtnTitle'     => 'Return to album index',

    'showImageBtn'          => 'Show image',
    'showImageBtnTitle'     => 'Show only image in a new window',

    'showHiResBtn'          => 'Original (#size#)',
    'showHiResBtnTitle'     => 'Show original high resolution image in a new window (#size#)',

    'showHiResDownloadBtn'      => 'Download (#size#)',
    'showHiResDownloadBtnTitle' => 'Download original high resolution image (#size#)',

    'showShowDetailsBtn'        => 'Show details',
    'showShowDetailsBtnTitle'   => 'Show EXIF image details: image date, shutter speed etc. (if available)',

    'showHideDetailsBtn'        => 'Hide details',
    'showHideDetailsBtnTitle'   => 'Hide EXIF image details',

    'showRotateBtn'             => 'Rotate',
    'showRotateBtnTitle'        => 'Rotate image 90 degrees clockwise',

    'showUpdateBtn'             => 'Update',
    'showUpdateBtnTitle'        => 'Regenerate resized image and thumbnail',

    'showExifFilename'          => 'File name: ',
    'showExifFilesize'          => 'File size: ',
    'showExifResolution'        => 'Resolution: ',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => 'Date: ',
    'showExifCamera'            => 'Camera model: ',
    'showExifISO'               => 'ISO: ',
    'showExifExposure'          => 'Exposure: ',
    'showExifAperture'          => 'Aperture: ',
    'showExifFocalLength'       => 'Focal length: ',
    'showExifFlashYes'          => 'Yes',
    'showExifFlashNo'           => 'No',
    'showExifFlash'             => 'Flash fired: ',
    'showExifDialogTitle'       => 'Original image details',

    'showImageTitleImage'       => 'Click to show the next image: #image#',
    'showImageTitleIndex'       => 'Click to return to the album index',


    // edit*.php
    'editTitle'                 => 'Edit #filename#',
    'editDlgTitle'              => 'Album definition file',
    'editFileLocation'          => 'File location',

    'editEditAsTextBtn'         => 'Edit as text',
    'editEditAsTextBtnTitle'    => 'Edit this file as a plain-text file',
    'editReindexNote'           => 'Please note that you need to reindex after changing image resizing settings',

    'editAlbumTitle'            => 'Album title:',
    'editAlbumDate'             => 'Date:',
    'editAlbumComment'          => 'Comment:',
    'editAlbumTitleImage'       => 'Title image:',
    'editAlbumDefault'          => 'Default album',
    'editAlbumUsers'            => 'Allowed users:',
    'editAlbumUsersNote'        => '(comma-separated user list, empty string or <B>all</B> = anonymous access, <B>valid-user</B>=any authenticated user)',

    'editCancelBtn'             => 'Cancel',
    'editSaveBtn'               => 'Save',

    'editThumbLink'             => '#filename# (Opens in a new window)',
    'editImgFilename'           => 'Filename<BR><small>(change to rename, clear to delete)</small>:',
    'editImgTitle'              => 'Title:',
    'editImgComment'            => 'Comment:',
    'editImgResize'             => 'Resize image',
    'editNewFileMessage'        => '( new file )',
    'editTop'                   => 'Top',

    'editRenameError'           => 'Unable to change filename to #filename# - invalid file extension',
    'editSaveError'             => 'An error occured saving album definition file #filename#',
    'editHTMLSep'               => 'HTML (separate page)',
    'editHTML'                  => 'HTML',
    'editText'                  => 'Text',

    // reindex.php
    'reindexTitle'              => 'DAlbum reindexing',
    'reindexDlgTitle'           => 'DAlbum reindexing',
    'reindexDlgComment'         => 'DAlbum reindexing searches data folders for new images, creates missing thumbnails and updates image database information.',
    'reindexDlgSpeed'           => 'Please specify reindexing speed below:',

    'reindexSpeed0'             => '<B>Fast</B>. Create only non-existing thumbnails and resized images. Do not verify integrity of image files.',
    'reindexSpeed1'             => '<B>Moderate</B>. Create only non-existing or corrupted thumbnails and resized images. Verify integrity of image files.',
    'reindexSpeed2'             => '<B>Slow</B>. Same as <B>Moderate</B> but also delete unreferenced thumbnails and resized images.',
    'reindexSpeed3'             => '<B>Extemely slow</B>. Recreate all thumbnails and resized images. Warning: it can take several hours!',

    'reindexCancelBtn'          => 'Cancel',
    'reindexStartBtn'           => 'Start',

    'reindexProgressTitle'      => 'DAlbum reindexing in progress',

    'reindexError'              => 'An error occured whilst creating thumbnail for image',
    'reindexRetry'              => 'Retry failed image',
    'reindexIgnore'             => 'Ignore error and continue',
    'reindexAgain'              => 'Restart reindexing',

    'reindexMainImageProblem'   => 'Uploaded image problem',
    'reindexResizedProblem'     => 'Resized image problem',
    'reindexThumbProblem'       => 'Thumbnail problem',

    'reindexCompleted'          => '<P>Operation completed.</P><P>Reindexing took #elapsed# seconds. Album tree was generated in #treeelapsed# seconds.</P>',
    'reindexStats'              => 'DAlbum statistics',
    'reindexStatsAlbums'        => 'Number of albums:',
    'reindexStatsImages'        => 'Number of images:',
    'reindexStatsOrigSize'      => 'Total size of original images:',
    'reindexStatsResizedSize'   => 'Total size of resized images:',
    'reindexStatsThumbSize'     => 'Total size of thumbnails:',

    'reindexStatusErrors'       => '<B>Status: </B> #errors# errors found:',

    'reindexStatusOK'           => '<B>Status: </B> Success. No errors were found.',
    'reindexSaveError'          => '<B>Error: </B>Unable to save #filename#',

    'reindexTHFilename'         => 'Filename',
    'reindexTHProblem'          => 'Problem',

    // customizations

    // Image comments
    'cCommentsImageComments'        => 'Image comments',
    'cCommentsLoginToAddComments'   => 'Please #loginbutton# to add your comments.<BR>&nbsp;',
    'cCommentsYourName'             => 'Your name:',
    'cCommentsComment'              => 'Comment:',
    'cCommentsSendButtonText'       => 'Send',
    'cCommentsDeleteButtonText'     => 'Delete',
    'cCommentsMailSubject'          => 'New comment about image #image# ( Album: #album# )',
    'cCommentsMailBody'             => "New comment posted by #user#, IP: #ip#, DNS: #dns#\n\n#body#\n\nPage URL: #url#\n",
    'cCommentsDateFormat'           => 'F j, Y, g:i a',

    // Slide show
    'cSlideshowSlideshow'           => '-- Slide show --',
    'cSlideshowSeconds'             => '#sec# seconds',
    'cSlideshowStopTitle'           => 'Click here to stop slide show',

    // Exif line (must be short)
    'cExiflineISOSpeedRatings'      => 'ISO:',
    'cExiflineExposure'             => 'E:',
    'cExiflineAperture'             => 'A:',
    'cExiflineFlash'                => 'Flash:',
    'cExiflineDateFormat'           => '%d %B %Y %H:%M:%S',
    'cExiflineFocal'                => 'F:',


    // Custom file types
    'cCustomClickToOpen'            => 'Click to open "#title#"',
    'cCustomOpenBtn'                => 'Open file',
    'cCustomOpenBtnTitle'           => 'Open file "#title#" in current window',

    // Highligh modified albums
    'cModifiedNew'                  => 'new!',
    'cModifiedUpdated'              => 'updated!',

    // ZIP
    'cZipBtn'                    => 'Download as ZIP (#size#)',
    'cZipBtnTitle'               => 'Download the whole album as ZIP archive (#size#)',

    ''  => ''
);

?>