<?php

/*  DAlbum Lithuanian language support file

    (c) Copyright 2005 by Pavel Baliko

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


/*

For proper displaying Lithuanian letters page must be in ISO-8859-13

*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'          => 'Prisijungti',
    'loginBtnTitle'     => 'Prisijungti',

    'logoutBtn'         => 'Atsijungti',
    'logoutBtnTitle'    => 'Atsijungti',

    'reindexBtn'        => 'Atnaujinti',
    'reindexBtnTitle'   => 'Ieškoti ir aktualizuoti naujus albumus (Reindex)',

    'usrmgrBtn'         => 'Vartotojai',
    'usrmgrBtnTitle'    => 'Valdyti vartotojus ir slaptažodžius',

    'closeWindowBtn'    => 'Uždaryti langą',
    'closeWindowBtnTitle'=> 'Uždaryti šį langą',

    'fullScreenBtn'         => 'Per visą ekraną',
    'fullScreenBtnTitle'    => 'Įjungti pilno ekrano režimą (tas pats kaip ir F11) ',

    'editDefBtn'            => 'Keisti',
    'editDefBtnTitle'       => 'Keisti albumo pavadinimą, komentarus ir tvarkyti nuotraukas',

    'indexUsername'         => 'Vartotojo vardas:',
    'page'                  => 'Nuotraukos #begin# - #end# iš #count#. &nbsp; Puslapis: &nbsp;',
    'noimages'              => 'Nuotraukų nėra',
    'noPublicImages'        => 'Prisijunkite, kad pamatytumėte nuotraukas.',
    'noscript'              => 'Apgailestaujame. Kad pamatytumėte šią puslapio dalį (Foto albumo medį) Jūs turite įjungti Javascript palaikymą.',

    'prevPageBtn'           => 'Atgal',
    'prevPageBtnTitle'      => 'Rodyti ankstesnį puslapį (#page#)',

    'nextPageBtn'           => 'Toliau',
    'nextPageBtnTitle'      => 'Rodyti kitą puslapį (#page#)',

    'statusLeft'            => 'Nuotraukų: <b>#TotalImages#</b>,  albumų: <b>#TotalAlbums#</b>',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'              => 'Pagrindinis puslapis',
    'username'              => 'Vartotojo vardas:',
    'password'              => 'Slaptažodis:',
    'bytes'                 => 'bytes',
    'KB'                    => 'KB',
    'MB'                    => 'MB',
    'pixels'                => 'pikselių',
    'errorReturn'           => 'Rodyti ankstesnį puslapį',

    /// Login.php
    'loginTitle'            =>  'Jungtis į: #title#',
    'loginAuthError'        =>  'Neteisingas Vartotojo vardas/slaptažodis',
    'loginBadUserName'      =>  'Jūsų vartotojo vardo ar slaptažodžio duomenų bazėje nėra.',
    'loginAgain'            =>  'Jungtis vėl',
    'loginNoCookiesWarning' =>  '<HR><B>Dėmesio: Jūsų naršyklėje slapukai (cookies) išjungti!</B><BR>Įjunkit slapukus ir atnaujinkit puslapi (F5).<BR><HR>',
    'loginLoginBtn'         => 'Prisijungti',
    'loginCancelBtn'        => 'Atšaukti',

    // pass.php
    'passTitle'             => 'Vartotojų valdymas',
    'passUserExists'        => 'Vartotojas #user# jau egzistuoja.',
    'passNotMatch'          => 'Nevienodi slaptažodžiai.',
    'passNoUserSelected'    => 'Nepasirinktas vartotojo vardas.',
    'passNoAdminDelete'     => 'Administratoriaus ištrinti negalima.',
    'passWriteError'        => 'Nėra priėjimo prie slaptažodžių failo!',
    'passError'             => '<B>Klaida: </B>#error#',
    'passAddBtn'            => 'Pridėti',
    'passDeleteBtn'         => 'Ištrinti',
    'passChangePwdBtn'      => 'Keisti slaptažodį',
    'passCloseBtn'          => 'Uždaryti',
    'passCancelBtn'         => 'Atšaukti',

    'passAddUserDlgTitle'   => 'Pridėti vartotoją',
    'passChangePwdDlgTitle' => 'Keisti slaptažodį',
    'passConfirmPassword'   => 'Patvirtinti slaptažodį:',

    // showimg.php
    'showPrevBtn'           => 'Atgal',
    'showPrevBtnTitle'      => 'Rodyti ankstesnę nuotrauką',

    'showNextBtn'           => 'Toliau',
    'showNextBtnTitle'      => 'Rodyti kitą nuotrauką',

    'showIndexBtn'          => 'Pagrindinis puslapis',
    'showIndexBtnTitle'     => 'Grįžti į pagrindinį puslapį',

    'showImageBtn'          => 'Rodyti nuotrauką',
    'showImageBtnTitle'     => 'Atidaro nuotrauką atskirame lange',

    'showHiResBtn'          => 'Originalus dydis (#size#)',
    'showHiResBtnTitle'     => 'Atidaro originalaus dydžio nuotrauką naujame lange',

    'showShowDetailsBtn'        => 'Rodyti detales',
    'showShowDetailsBtnTitle'   => 'Rodyti EXIF informaciją: datą, užrakto greitį ir pan. (jei tokia informacija išsaugota).',

    'showHideDetailsBtn'        => 'Slėpti detales',
    'showHideDetailsBtnTitle'   => 'Slėpti EXIF informaciją',

    'showRotateBtn'             => 'Pasukti',
    'showRotateBtnTitle'        => 'Pasukti nuotrauką 90 laipsnių kampu.',

    'showUpdateBtn'             => 'Atnaujinti',
    'showUpdateBtnTitle'        => 'Atnaujinti nuotrauką ir jos miniatiūrą',

    'showExifFilename'          => 'Failo pavadinimas: ',
    'showExifFilesize'          => 'Failo dydis: ',
    'showExifResolution'        => 'Skiriamoji geba: ',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => 'Data: ',
    'showExifCamera'            => 'Fotoaparato modelis: ',
    'showExifExposure'          => 'Išlaikymas (ekspozicijos laikas): ',
    'showExifAperture'          => 'Diafragma: ',
    'showExifFocalLength'       => 'Židinio nuotolis: ',
    'showExifFlashYes'          => 'Taip',
    'showExifFlashNo'           => 'Ne',
    'showExifFlash'             => 'Blykstė: ',
    'showExifDialogTitle'       => 'Originalios nuotraukos detalės',

    'showImageTitleImage'       => 'Spausti, kad atsidarytų kita nuotrauka: #image#',
    'showImageTitleIndex'       => 'Spausti, kad grįžti į pagrindinį puslapį',


    // edit*.php
    'editTitle'                 => 'Keisti #filename#',
    'editDlgTitle'              => 'Failas su albumo duomenimis',
    'editFileLocation'          => 'Failo adresas (location)',

    'editEditAsTextBtn'         => 'Keisti kaip tekstą',
    'editEditAsTextBtnTitle'    => 'Keisti kaip tekstinį failą',
    'editReindexNote'           => 'Pakeitus albumų duomenis reikia Atnaujinti (Reindex)',

    'editAlbumTitle'            => 'Albumo pavadinimas:',
    'editAlbumDate'             => 'Data:',
    'editAlbumComment'          => 'Komentaras:',
    'editAlbumTitleImage'       => 'Nuotraukos pavadinimas:',
    'editAlbumDefault'          => 'Numatytas albumas (Default):',
    'editAlbumUsers'            => 'Leistini vartotojai:',
    'editAlbumUsersNote'        => '(Vartotojų vardų, atskirtų kableliais, sąrašas, tuščias laukas arba <B>all</B> = visi lankytojai, <B>valid-user</B>=bet kuris registruotas vartotojas)',

    'editCancelBtn'             => 'Atšaukti',
    'editSaveBtn'               => 'Įrašyti',

    'editThumbLink'             => '#filename# (atidarytas naujame lange)',
    'editImgFilename'           => 'Failas<BR><small>(change=pervadinti, clear=ištrinti)</small>:',
    'editImgTitle'              => 'Pavadinimas:',
    'editImgComment'            => 'Komentaras:',
    'editImgResize'             => 'Pakeisti failo dydį',
    'editNewFileMessage'        => '( naujas failas )',
    'editTop'                   => 'Į viršų',

    'editRenameError'           => 'Neįmanoma pakeisti failo pavadinimą į #filename# - neteisingas plėtinys (extention)',
    'editSaveError'             => 'Klaida išsaugant failą su albumo #filename# duomenimis',
    'editHTML'                  => 'HTML',
    'editText'                  => 'Tekstas',

    // reindex.php
    'reindexTitle'              => 'DAlbum - atnaujinimas',
    'reindexDlgTitle'           => 'DAlbum - atnaujinimas',
    'reindexDlgComment'         => 'DAlbum ieško naujų nuotraukų, sukuria trūkstančias miniatiūras ir aktualizuoja informaciją apie nuotraukas ir albumus.',
    'reindexDlgSpeed'           => 'Išsirinkti atnaujinimo greitį:',

    'reindexSpeed0'             => '<B>Greitas</B>. Generuoja trūkstančias miniatiūras ir sumažintas nuotraukas.',
    'reindexSpeed1'             => '<B>Vidutinis</B>. Generuoja trūkstančias bei pažeistas miniatiūras ir sumažintas nuotraukas. Tikrina failus.',
    'reindexSpeed2'             => '<B>Lėtas</B>. Generuoja trūkstančias bei pažeistas miniatiūras ir sumažintas nuotraukas. Tikrina bei ištrina nereikalingus failus.',
    'reindexSpeed3'             => '<B>LABAI lėtas</B>. Generuojama naujas miniatiūras visiems failams. Dėmesio! Tai gali užtrukti labai ilgai!',

    'reindexCancelBtn'          => 'Atšaukti',
    'reindexStartBtn'           => 'Pradėti',

    'reindexProgressTitle'      => 'Vyksta atnaujinimas...',

    'reindexError'              => 'Klaida kuriant nuotraukos miniatiūrą!',
    'reindexRetry'              => 'Bandyti iš naujo generuoti pažeistą miniatiūrą',
    'reindexIgnore'             => 'Ignoruoti klaidą',
    'reindexAgain'              => 'Atnaujinti',

    'reindexMainImageProblem'   => 'Problema siunčiant failą',
    'reindexResizedProblem'     => 'Problema keičiant failo dydį',
    'reindexThumbProblem'       => 'Problema su miniatiūra',

    'reindexCompleted'          => '<P>Atnaujinimas baigtas.</P><P>Atnaujinimas truko: #elapsed# sek. Albumų katalogas sugeneruotas per: #treeelapsed# sek.</P>',
    'reindexStats'              => 'Statistika',
    'reindexStatsAlbums'        => 'Viso albumų:',
    'reindexStatsImages'        => 'Viso nuotraukų:',
    'reindexStatsOrigSize'      => 'Bendras originalių failų dydis:',
    'reindexStatsResizedSize'   => 'Bendras sumažintų nuotraukų failų dydis:',
    'reindexStatsThumbSize'     => 'Bendras miniatiūrų failų dydis:',

    'reindexStatusErrors'       => '<B>Dėmesio! Rasta klaidų: </B> #errors# ',

    'reindexStatusOK'           => '<B>Atnaujinimas sėkmingai baigtas. </B>',
    'reindexSaveError'          => '<B>Klaida: </B>neįmanoma įrašyti #filename#',

    'reindexTHFilename'         => 'Failo pavadinimas',
    'reindexTHProblem'          => 'Problema',

    // customizations

    // Image comments
    'cCommentsImageComments'        => 'Nuotraukos komentarai',
    'cCommentsLoginToAddComments'   => 'Kad galėtumėte pridėti savo komentarą, turite #loginbutton# .<BR>&nbsp;',
    'cCommentsYourName'             => 'Jūsų vardas:',
    'cCommentsComment'              => 'Komentaras:',
    'cCommentsSendButtonText'       => 'Siųsti',
    'cCommentsDeleteButtonText'     => 'Trinti',
    'cCommentsMailSubject'          => 'Naujas komentaras apie #image# ( Albumas: #album# )',
    'cCommentsMailBody'             => "Naują komentarą įdėjo #user#, IP: #ip#, DNS: #dns#\n\n#body#\n\nPage URL: #url#\n",
    'cCommentsDateFormat'           => 'F j, Y, g:i a',

    // Slide show
    'cSlideshowSlideshow'           => '-- Slide show --',
    'cSlideshowSeconds'             => '#sec# sek.',

    // Exif line (must be short)
    'cExiflineISOSpeedRatings'      => 'ISO:',
    'cExiflineExposure'             => 'Išlaikymas (ekspozicijos laikas):',
    'cExiflineAperture'             => 'Diafragma:',
    'cExiflineFlash'                => 'Blykstė:',
    'cExiflineDateFormat'           => '%d %B %Y %H:%M:%S',

    // Custom file types
    'cCustomClickToOpen'            => 'Atidaryti "#title#"',
    'cCustomOpenBtn'                => 'Atidaryti failą',
    'cCustomOpenBtnTitle'           => 'Atidaryti failą "#title#" aktyviame lange',

    // Highligh modified albums
    'cModifiedNew'                  => 'naujas!',
    'cModifiedUpdated'              => 'atnaujintas!',

    ''  => ''
);

?>
