<?php

/*  DAlbum Lithuanian language support file

    (c) Copyright 2005 by Pavel Baliko

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


/*

For proper displaying Lithuanian letters page must be in ISO-8859-13

*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'          => 'Prisijungti',
    'loginBtnTitle'     => 'Prisijungti',

    'logoutBtn'         => 'Atsijungti',
    'logoutBtnTitle'    => 'Atsijungti',

    'reindexBtn'        => 'Atnaujinti',
    'reindexBtnTitle'   => 'Ieðkoti ir aktualizuoti naujus albumus (Reindex)',

    'usrmgrBtn'         => 'Vartotojai',
    'usrmgrBtnTitle'    => 'Valdyti vartotojus ir slaptaþodþius',

    'closeWindowBtn'    => 'Uþdaryti langà',
    'closeWindowBtnTitle'=> 'Uþdaryti ðá langà',

    'fullScreenBtn'         => 'Per visà ekranà',
    'fullScreenBtnTitle'    => 'Ájungti pilno ekrano reþimà (tas pats kaip ir F11) ',

    'editDefBtn'            => 'Keisti',
    'editDefBtnTitle'       => 'Keisti albumo pavadinimà, komentarus ir tvarkyti nuotraukas',

    'indexUsername'         => 'Vartotojo vardas:',
    'page'                  => 'Nuotraukos #begin# - #end# ið #count#. &nbsp; Puslapis: &nbsp;',
    'noimages'              => 'Nuotraukø nëra',
    'noPublicImages'        => 'Prisijunkite, kad pamatytumëte nuotraukas.',
    'noscript'              => 'Apgailëstaujame. Kad pamatytumëte ðià puslapio dalá (Foto albumo medá) Jûs turite ájungti Javascript palaikymà.',

    'prevPageBtn'           => 'Atgal',
    'prevPageBtnTitle'      => 'Rodyti ankstesná puslapá (#page#)',

    'nextPageBtn'           => 'Toliau',
    'nextPageBtnTitle'      => 'Rodyti kità puslapá (#page#)',

    'statusLeft'            => 'Nuotraukø: <b>#TotalImages#</b>,  albumø: <b>#TotalAlbums#</b>',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'              => 'Pagrindinis puslapis',
    'username'              => 'Vartotojo vardas:',
    'password'              => 'Slaptaþodis:',
    'bytes'                 => 'bytes',
    'KB'                    => 'KB',
    'MB'                    => 'MB',
    'pixels'                => 'pikseliø',
    'errorReturn'           => 'Rodyti ankstesná puslapá',

    /// Login.php
    'loginTitle'            =>  'Jungtis á: #title#',
    'loginAuthError'        =>  'Neteisingas Vartotojo vardas/slaptaþodis',
    'loginBadUserName'      =>  'Jûsø vartotojo vardo ar slaptaþodþio duomenø bazëje nëra.',
    'loginAgain'            =>  'Jungtis vël',
    'loginNoCookiesWarning' =>  '<HR><B>Dëmesio: Jûsø narðyklëje slapukai (cookies) iðjungti!</B><BR>Ájunkit slapukus ir atnaujinkit puslapi (F5).<BR><HR>',
    'loginLoginBtn'         => 'Prisijungti',
    'loginCancelBtn'        => 'Atðaukti',

    // pass.php
    'passTitle'             => 'Vartotojø valdymas',
    'passUserExists'        => 'Vartotojas #user# jau egzistuoja.',
    'passNotMatch'          => 'Nevienodi slaptaþodþiai.',
    'passNoUserSelected'    => 'Nepasirinktas vartotojo vardas.',
    'passNoAdminDelete'     => 'Administratoriaus iðtrinti negalima.',
    'passWriteError'        => 'Nëra priëjimo prie slaptaþodþiø failo!',
    'passError'             => '<B>Klaida: </B>#error#',
    'passAddBtn'            => 'Pridëti',
    'passDeleteBtn'         => 'Iðtrinti',
    'passChangePwdBtn'      => 'Keisti slaptaþodá',
    'passCloseBtn'          => 'Uþdaryti',
    'passCancelBtn'         => 'Atðaukti',

    'passAddUserDlgTitle'   => 'Pridëti vartotojà',
    'passChangePwdDlgTitle' => 'Keisti slaptaþodá',
    'passConfirmPassword'   => 'Patvirtinti slaptaþodá:',

    // showimg.php
    'showPrevBtn'           => 'Atgal',
    'showPrevBtnTitle'      => 'Rodyti ankstesnæ nuotraukà',

    'showNextBtn'           => 'Toliau',
    'showNextBtnTitle'      => 'Rodyti kità nuotraukà',

    'showIndexBtn'          => 'Pagrindinis puslapis',
    'showIndexBtnTitle'     => 'Gráþti á pagrindiná puslapá',

    'showImageBtn'          => 'Rodyti nuotraukà',
    'showImageBtnTitle'     => 'Atidaro nuotraukà atskirame lange',

    'showHiResBtn'          => 'Originalus dydis (#size#)',
    'showHiResBtnTitle'     => 'Atidaro originalaus dydþio nuotraukà naujame lange',

    'showShowDetailsBtn'        => 'Rodyti detales',
    'showShowDetailsBtnTitle'   => 'Rodyti EXIF informacijà: datà, uþrakto greitá ir pan. (jei tokia informacija iðsaugota).',

    'showHideDetailsBtn'        => 'Slëpti detales',
    'showHideDetailsBtnTitle'   => 'Slëpti EXIF informacijà',

    'showRotateBtn'             => 'Pasukti',
    'showRotateBtnTitle'        => 'Pasukti nuotraukà 90 laipsniø kampu.',

    'showUpdateBtn'             => 'Atnaujinti',
    'showUpdateBtnTitle'        => 'Atnaujinti nuotraukà ir jos miniatiûrà',

    'showExifFilename'          => 'Failo pavadinimas: ',
    'showExifFilesize'          => 'Failo dydis: ',
    'showExifResolution'        => 'Skiriamoji geba: ',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => 'Data: ',
    'showExifCamera'            => 'Fotoaparato modelis: ',
    'showExifExposure'          => 'Iðlaikymas (ekspozicijos laikas): ',
    'showExifAperture'          => 'Diafragma: ',
    'showExifFocalLength'       => 'Þidinio nuotolis: ',
    'showExifFlashYes'          => 'Taip',
    'showExifFlashNo'           => 'Ne',
    'showExifFlash'             => 'Blykstë: ',
    'showExifDialogTitle'       => 'Originalios nuotraukos detalës',

    'showImageTitleImage'       => 'Spausti, kad atsidarytø kita nuotrauka: #image#',
    'showImageTitleIndex'       => 'Spausti, kad gráþti á pagrindiná puslapá',


    // edit*.php
    'editTitle'                 => 'Keisti #filename#',
    'editDlgTitle'              => 'Failas su albumo duomenimis',
    'editFileLocation'          => 'Failo adresas (location)',

    'editEditAsTextBtn'         => 'Keisti kaip tekstà',
    'editEditAsTextBtnTitle'    => 'Keisti kaip tekstiná failà',
    'editReindexNote'           => 'Pakeitus albumø duomenis reikia Atnaujinti (Reindex)',

    'editAlbumTitle'            => 'Albumo pavadinimas:',
    'editAlbumDate'             => 'Data:',
    'editAlbumComment'          => 'Komentaras:',
    'editAlbumTitleImage'       => 'Nuotraukos pavadinimas:',
    'editAlbumDefault'          => 'Numatytas albumas (Default):',
    'editAlbumUsers'            => 'Leistini vartotojai:',
    'editAlbumUsersNote'        => '(Vartotojø vardø, atskirtø kableliais, sàraðas, tuðèias laukas arba <B>all</B> = visi lankytojai, <B>valid-user</B>=bet kuris registruotas vartotojas)',

    'editCancelBtn'             => 'Atðaukti',
    'editSaveBtn'               => 'Áraðyti',

    'editThumbLink'             => '#filename# (atidarytas naujame lange)',
    'editImgFilename'           => 'Failas<BR><small>(change=pervadinti, clear=iðtrinti)</small>:',
    'editImgTitle'              => 'Pavadinimas:',
    'editImgComment'            => 'Komentaras:',
    'editImgResize'             => 'Pakeisti failo dydá',
    'editNewFileMessage'        => '( naujas failas )',
    'editTop'                   => 'Á virðø',

    'editRenameError'           => 'Neámanoma pakeisti failo pavadinimà á #filename# - neteisingas plëtinys (extention)',
    'editSaveError'             => 'Klaida iðsaugant failà su albumo #filename# duomenimis',
    'editHTML'                  => 'HTML',
    'editText'                  => 'Tekstas',

    // reindex.php
    'reindexTitle'              => 'DAlbum - atnaujinimas',
    'reindexDlgTitle'           => 'DAlbum - atnaujinimas',
    'reindexDlgComment'         => 'DAlbum ieðko naujø nuotraukø, sukuria trûkstanèias miniatiûras ir aktualizuoja informacijà apie nuotraukas ir albumus.',
    'reindexDlgSpeed'           => 'Iðsirinkti atnaujinimo greitá:',

    'reindexSpeed0'             => '<B>Greitas</B>. Generuoja trûkstanèias miniatiûras ir sumaþintas nuotraukas.',
    'reindexSpeed1'             => '<B>Vidutinis</B>. Generuoja trûkstanèias bei paþeistas miniatiûras ir sumaþintas nuotraukas. Tikrina failus.',
    'reindexSpeed2'             => '<B>Lëtas</B>. Generuoja trûkstanèias bei paþeistas miniatiûras ir sumaþintas nuotraukas. Tikrina bei iðtrina nereikalingus failus.',
    'reindexSpeed3'             => '<B>LABAI lëtas</B>. Generuojama naujas miniatiûras visiems failams. Dëmesio! Tai gali uþtrukti labai ilgai!',

    'reindexCancelBtn'          => 'Atðaukti',
    'reindexStartBtn'           => 'Pradëti',

    'reindexProgressTitle'      => 'Vyksta atnaujinimas...',

    'reindexError'              => 'Klaida kuriant nuotraukos miniatiûrà!',
    'reindexRetry'              => 'Bandyti ið naujo generuoti paþeistà miniatiûrà',
    'reindexIgnore'             => 'Ignoruoti klaidà',
    'reindexAgain'              => 'Atnaujinti',

    'reindexMainImageProblem'   => 'Problema siunèiant failà',
    'reindexResizedProblem'     => 'Problema keièiant failo dydá',
    'reindexThumbProblem'       => 'Problema su miniatiûra',

    'reindexCompleted'          => '<P>Atnaujinimas baigtas.</P><P>Atnaujinimas truko: #elapsed# sek. Albumø katalogas sugeneruotas per: #treeelapsed# sek.</P>',
    'reindexStats'              => 'Statistika',
    'reindexStatsAlbums'        => 'Viso albumø:',
    'reindexStatsImages'        => 'Viso nuotraukø:',
    'reindexStatsOrigSize'      => 'Bendras originaliø failø dydis:',
    'reindexStatsResizedSize'   => 'Bendras sumaþintø nuotraukø failø dydis:',
    'reindexStatsThumbSize'     => 'Bendras miniatiûrø failø dydis:',

    'reindexStatusErrors'       => '<B>Dëmesio! Rasta klaidø: </B> #errors# ',

    'reindexStatusOK'           => '<B>Atnaujinimas sëkmingai baigtas. </B>',
    'reindexSaveError'          => '<B>Klaida: </B>neámanoma áraðyti #filename#',

    'reindexTHFilename'         => 'Failo pavadinimas',
    'reindexTHProblem'          => 'Problema',

    // customizations

    // Image comments
    'cCommentsImageComments'        => 'Nuotraukos komentarai',
    'cCommentsLoginToAddComments'   => 'Kad galëtumëte pridëti savo komentarà, turite #loginbutton# .<BR>&nbsp;',
    'cCommentsYourName'             => 'Jûsø vardas:',
    'cCommentsComment'              => 'Komentaras:',
    'cCommentsSendButtonText'       => 'Siøsti',
    'cCommentsDeleteButtonText'     => 'Trinti',
    'cCommentsMailSubject'          => 'Naujas komentaras apie #image# ( Albumas: #album# )',
    'cCommentsMailBody'             => "Naujà komentarà ádëjo #user#, IP: #ip#, DNS: #dns#\n\n#body#\n\nPage URL: #url#\n",
    'cCommentsDateFormat'           => 'F j, Y, g:i a',

    // Slide show
    'cSlideshowSlideshow'           => '-- Slide show --',
    'cSlideshowSeconds'             => '#sec# sek.',

    // Exif line (must be short)
    'cExiflineISOSpeedRatings'      => 'ISO:',
    'cExiflineExposure'             => 'Iðlaikymas (ekspozicijos laikas):',
    'cExiflineAperture'             => 'Diafragma:',
    'cExiflineFlash'                => 'Blykstë:',
    'cExiflineDateFormat'           => '%d %B %Y %H:%M:%S',

    // Custom file types
    'cCustomClickToOpen'            => 'Atidaryti "#title#"',
    'cCustomOpenBtn'                => 'Atidaryti failà',
    'cCustomOpenBtnTitle'           => 'Atidaryti failà "#title#" aktyviame lange',

    // Highligh modified albums
    'cModifiedNew'                  => 'naujas!',
    'cModifiedUpdated'              => 'atnaujintas!',

    ''  => ''
);

?>