<?php

/*  DAlbum Polish language support file

    (c) Copyright 2003 by Tomek Winiarski

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


/*

For proper displaying Polish letters page must be in ISO-8859-2

*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'          => 'Log in',
    'loginBtnTitle'     => 'Log in',

    'logoutBtn'         => 'Log out',
    'logoutBtnTitle'    => 'Log out',

    'reindexBtn'        => 'Reindex',
    'reindexBtnTitle'   => 'Przeszukiwanie i aktualizacja albumów',

    'usrmgrBtn'         => 'U¿ytkownicy',
    'usrmgrBtnTitle'    => 'Zarz±dzanie u¿ytkownikami i has³ami',

    'closeWindowBtn'    => 'Zamknij okno',
    'closeWindowBtnTitle'=> 'Zamyka to okno',

    'fullScreenBtn'         => 'Pe³ny ekran',
    'fullScreenBtnTitle'    => 'Prze³acza tê stronê na pe³ny ekran (to samo powoduje naci¶niêcie klawisza F11) ',

    'editDefBtn'            => 'Edycja',
    'editDefBtnTitle'       => 'Edycja nazwy albumu, komentarzy i zarz±dzanie zdjêciami',

    'indexUsername'         => 'U¿ytkownik:',
    'page'                  => 'Zdjêcia #begin# - #end# z #count#. &nbsp; Strona: &nbsp;',
    'noimages'              => 'Brak zdjêæ',
    'noPublicImages'        => 'Brak zdjêæ dostêpnych bez uprawnieñ. Proszê siê zalogowaæ.',
    'noscript'              => 'Przepraszam. Wy¶wietlanie folderów dzia³a tylko z przegl±darkami obs³uguj±cymi JavaScript<BR><BR>Proszê w³±czyæ obs³ugê JavaSript-u.',

    'prevPageBtn'           => 'Wstecz',
    'prevPageBtnTitle'      => 'Powrót do porzedniej strony (#page#)',

    'nextPageBtn'           => 'Dalej',
    'nextPageBtnTitle'      => 'Przejd¼ do nastêpnej strony (#page#)',

    'statusLeft'            => 'Zdjêæ: <b>#TotalImages#</b>,  albumów: <b>#TotalAlbums#</b>',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'              => 'Strona g³ówna',
    'username'              => 'U¿ytkownik:',
    'password'              => 'Has³o:',
    'bytes'                 => 'bytes',
    'KB'                    => 'KB',
    'MB'                    => 'MB',
    'pixels'                => 'pikseli',
    'errorReturn'           => 'Powrót do porzedniej strony',

    /// Login.php
    'loginTitle'            =>  'Logowanie do: #title#',
    'loginAuthError'        =>  'Z³y login/has³o',
    'loginBadUserName'      =>  'Tój login lub has³o nie zosta³y odnalezione.',
    'loginAgain'            =>  'Ponowne logowanie',
    'loginNoCookiesWarning' =>  '<HR><B>Ostrze¿enie: w przegl±darce wy³±czone s± cookies!</B><BR>do przegl±dania tych stron cookies musz± byæ w³±czone.<BR>Po ich w³±czeniu od¶wie¿ stronê.<BR><HR>',
    'loginLoginBtn'         => 'Logowanie',
    'loginCancelBtn'        => 'Anuluj',

    // pass.php
    'passTitle'             => 'Zarz±dzanie u¿ytkownikami',
    'passUserExists'        => 'u¿ytkownik #user# ju¿ istnieje.',
    'passNotMatch'          => 'Has³o nie pasuj±.',
    'passNoUserSelected'    => 'Nie wybrano u¿ytkownika.',
    'passNoAdminDelete'     => 'G³ówny administrator nie mo¿e byæ usuniêty.',
    'passWriteError'        => 'Brak dostêpu do pliku z has³ami!',
    'passError'             => '<B>B³±d: </B>#error#',
    'passAddBtn'            => 'Dodaj',
    'passDeleteBtn'         => 'Skasuj',
    'passChangePwdBtn'      => 'Zmieñ has³o',
    'passCloseBtn'          => 'Zamknij',
    'passCancelBtn'         => 'Anuluj',

    'passAddUserDlgTitle'   => 'Dodaj u¿ytkownika',
    'passChangePwdDlgTitle' => 'Zmieñ has³o',
    'passConfirmPassword'   => 'Potwierd¼ has³o:',

    // showimg.php
    'showPrevBtn'           => 'Wstecz',
    'showPrevBtnTitle'      => 'Poka¿ poprzednie zdjêcie',

    'showNextBtn'           => 'Dalej',
    'showNextBtnTitle'      => 'Poka¿ nastêpne zdjêcie',

    'showIndexBtn'          => 'Miniatury',
    'showIndexBtnTitle'     => 'Powrót do strony z miniaturkami',

    'showImageBtn'          => 'Poka¿ zdjêcie',
    'showImageBtnTitle'     => 'Otwiera tylko zdjêcie w osobnym oknie',

    'showHiResBtn'          => 'Oryginalny rozmiar (#size#)',
    'showHiResBtnTitle'     => 'Otwiera zdjêcie w oryginalnym rozmiarze (osobne okno)',

    'showShowDetailsBtn'        => 'Poka¿ szczegó³y',
    'showShowDetailsBtnTitle'   => 'Wy¶wietla informacje EXIF: datê, przes³onê, czu³o¶æ, itp (je¶li takie dane s± zachowane).',

    'showHideDetailsBtn'        => 'Ukryj szczegó³y',
    'showHideDetailsBtnTitle'   => 'Ukrywa informacje EXIF',

    'showRotateBtn'             => 'Obrót',
    'showRotateBtnTitle'        => 'Obraca zdjêcie o 90 stopni.',

    'showUpdateBtn'             => 'Od¶wie¿',
    'showUpdateBtnTitle'        => 'Od¶wie¿a zdjêcie i jego miniaturkê',

    'showExifFilename'          => 'Nazwa pliku: ',
    'showExifFilesize'          => 'Rozmiar pliku: ',
    'showExifResolution'        => 'Rozdzielczo¶æ: ',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => 'Data: ',
    'showExifCamera'            => 'Model aparatu: ',
    'showExifExposure'          => 'Czas na¶wietlania: ',
    'showExifAperture'          => 'Przes³ona: ',
    'showExifFocalLength'       => 'Ogniskowa: ',
    'showExifFlashYes'          => 'Tak',
    'showExifFlashNo'           => 'Nie',
    'showExifFlash'             => 'Lampa: ',
    'showExifDialogTitle'       => 'Informacje o zdjêciu',

    'showImageTitleImage'       => 'Kliknij aby pokazaæ nastêpne zdjêcie: #image#',
    'showImageTitleIndex'       => 'Kliknij aby powróciæ do miniaturek',


    // edit*.php
    'editTitle'                 => 'Edytcja #filename#',
    'editDlgTitle'              => 'Plik opisuj±cy album',
    'editFileLocation'          => 'Po³o¿enie pliku',

    'editEditAsTextBtn'         => 'Edycja pliku tekstowego',
    'editEditAsTextBtnTitle'    => 'Edycja pliku opisuj±cego w formie pliku tekstowego',
    'editReindexNote'           => 'Pamiêtaj o od¶wie¿eniu albumów po zmianach w plikach opisuj±cych albumy',

    'editAlbumTitle'            => 'Tytu³ albumu:',
    'editAlbumDate'             => 'Data:',
    'editAlbumComment'          => 'Komentarz:',
    'editAlbumTitleImage'       => 'Tytu³ zdjêcia:',
    'editAlbumDefault'          => 'Album domy¶lny:',
    'editAlbumUsers'            => 'Dopuszczeni u¿ytkownicy:',
    'editAlbumUsersNote'        => '(lista u¿ytkowników odzielona przecinkami, brak wpisu lub <B>all</B> = wszyscy odwiedzaj±cy, <B>valid-user</B>=dowolny zarejestrowany u¿ytkownik)',

    'editCancelBtn'             => 'Anuluj',
    'editSaveBtn'               => 'Zapisz',

    'editThumbLink'             => '#filename# (Otwarty w nowym oknie)',
    'editImgFilename'           => 'Plik<BR><small>(change to rename, clear to delete)</small>:',
    'editImgTitle'              => 'Tytu³:',
    'editImgComment'            => 'Komentarz:',
    'editImgResize'             => 'Zmiana rozmiaru',
    'editNewFileMessage'        => '( nowy plik )',
    'editTop'                   => 'Góra',

    'editRenameError'           => 'Unable to change filenaname to #filename# - invalid file extension',
    'editSaveError'             => 'An error occured saving album definition file #filename#',
    'editHTML'                  => 'HTML',
    'editText'                  => 'Text',

    // reindex.php
    'reindexTitle'              => 'DAlbum - od¶wie¿anie',
    'reindexDlgTitle'           => 'DAlbum - od¶wie¿anie',
    'reindexDlgComment'         => 'DAlbum wyszukuje nowe zdjêcia, tworzy brakuj±ce miniaturki i uaktualnia informacje o albumach i zdjêciach.',
    'reindexDlgSpeed'           => 'Wybierz prêdko¶æ od¶wie¿ania:',

    'reindexSpeed0'             => '<B>Szybkie</B>. Generowane s± wy³±cznie nie istniej±ce miniatury i zmniejszone zdjêcia. Nie jest przeprowadzana weryfikacja plików',
    'reindexSpeed1'             => '<B>¦rednie</B>. Generowane s± nie istniej±ce lub uszkodzone miniatury i zmniejszone zdjêcia. Przeprowadzana jest weryfikacja plików.',
    'reindexSpeed2'             => '<B>Wolne</B>. Podobnie jak <B>¶rednie</B> dodatkowo kasowane s± niepotrzebne pliki.',
    'reindexSpeed3'             => '<B>BARDZO wolne</B>. Generowane s± od nowa miniatury dla WSZYSTKICH zdjêæ. Uwaga! mo¿e to potrwaæ bardzo d³ugo!',

    'reindexCancelBtn'          => 'Anuluj',
    'reindexStartBtn'           => 'Start',

    'reindexProgressTitle'      => 'Od¶wie¿anie...',

    'reindexError'              => 'B³±d przy tworzeniu miniatury zdjêcia!',
    'reindexRetry'              => 'Ponów tworzenie tylko zepsutych miniatur',
    'reindexIgnore'             => 'Zignoruj b³±d',
    'reindexAgain'              => 'Ponowne od¶wie¿anie',

    'reindexMainImageProblem'   => 'Problem z wgraniem zdjêcia',
    'reindexResizedProblem'     => 'Problem ze zmian± rozmiaru zdjêcia',
    'reindexThumbProblem'       => 'Problem z miniaturk±',

    'reindexCompleted'          => '<P>Od¶wie¿anie zakoñczone.</P><P>Od¶wie¿anie zajê³o: #elapsed# sek. Katalog albumów wygenerowny w: #treeelapsed# sek.</P>',
    'reindexStats'              => 'Statystyka',
    'reindexStatsAlbums'        => 'Ilo¶æ albumów:',
    'reindexStatsImages'        => 'Ilo¶æ zdjêæ:',
    'reindexStatsOrigSize'      => 'Ca³kowita objêto¶æ oryginalnych plików:',
    'reindexStatsResizedSize'   => 'Ca³kowita objêto¶æ plików zdjeæ zmniejszanych:',
    'reindexStatsThumbSize'     => 'Ca³kowita objêto¶æ plików miniaturek:',

    'reindexStatusErrors'       => '<B>Uwaga! Znaleziono b³edów: </B> #errors# ',

    'reindexStatusOK'           => '<B>Od¶wie¿anie zakoñczone sukcesem. </B>',
    'reindexSaveError'          => '<B>B³±d: </B>nie mo¿na zapisaæ: #filename#',

    'reindexTHFilename'         => 'Filename',
    'reindexTHProblem'          => 'Problem',

    ''  => ''
);

?>