<?php

/*  DAlbum Chinese-Big5 language support file

    (c) Copyright 2003 by DeltaX Inc.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'      => '登录',
    'loginBtnTitle'     => '登录',

    'logoutBtn'         => '注销',
    'logoutBtnTitle'    => '注销',

    'reindexBtn'        => '重建索引',
    'reindexBtnTitle'   => '找寻新的图片并更新至 DAlbum 数据库',

    'usrmgrBtn'         => '用户',
    'usrmgrBtnTitle'    => '新增／移除用户，或改变密码',

    'closeWindowBtn'    => '关闭全屏幕',
    'closeWindowBtnTitle'   => '关闭全屏幕',

    'fullScreenBtn'     => '全屏幕',
    'fullScreenBtnTitle'    => '以全屏幕开启此页，效果与按 F11 相同',

    'editDefBtn'        => '编辑',
    'editDefBtnTitle'   => '修改相簿名称，备忘，以及管理相簿内的图片。',

    'indexUsername'     => '用户：',
    'page'          => '显示第 #begin# - #end# 个项目，总共有 #count# 个项目。&nbsp;页数：',
    'noimages'      => '没有图片',
    'noPublicImages'    => '没有公开的图片，请登录。',
    'noscript'      => '对不起，您的浏览器需要开启 Javascript 的功能，才能显示树状目录。<BR><BR>请于浏览器选项开启此功能。',

    'prevPageBtn'           => '&lt;&lt;',
    'prevPageBtnTitle'      => '#page#',

    'nextPageBtn'           => '&gt;&gt;',
    'nextPageBtnTitle'      => '(#page#)',
    'statusLeft'            => '共有 <b>#TotalImages#</b> 分别图片存放于 <b>#TotalAlbums#</b> 个相簿',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'          => '回到主页',
    'username'          => '用户名称：',
    'password'          => '密码：',
    'bytes'             => '字节',
    'KB'                => 'KB',
    'MB'                => 'MB',
    'pixels'            => '像素',
    'errorReturn'           => '回到上一页',

    /// Login.php
    'loginTitle'            => '登录至 #title#',
    'loginAuthError'        => '认证错误',
    'loginBadUserName'      => '用户名称或密码错误',
    'loginAgain'            => '重新登录',
    'loginNoCookiesWarning'     =>  '<HR><B>警告：您的浏览器已关掉 Cookies 功能！</B><BR>请于浏览器选项开启 Cookies 功能，再重新整理此页。<BR><HR>',
    'loginLoginBtn'         => '登入',
    'loginCancelBtn'        => '取消',

    // pass.php
    'passTitle'         => '用户管理',
    'passUserExists'        => '#user# 已经存在',
    'passNotMatch'          => '密码不正确',
    'passNoUserSelected'        => '没有选择用户',
    'passNoAdminDelete'     => '不能删除主要的 DAlbum 管理员！',
    'passWriteError'        => '无法写入密码文件！',
    'passError'             => '<B>错误：</B>#error#',
    'passAddBtn'            => '增加',
    'passDeleteBtn'         => '删除',
    'passChangePwdBtn'      => '更改密码',
    'passCloseBtn'          => '关闭',
    'passCancelBtn'         => '取消',

    'passAddUserDlgTitle'       => '增加用户',
    'passChangePwdDlgTitle'     => '更改密码',
    'passConfirmPassword'       => '确认密码：',

    // showimg.php
    'showPrevBtn'           => '上一页',
    'showPrevBtnTitle'      => '显示上一张图片',

    'showNextBtn'           => '下一页',
    'showNextBtnTitle'      => '显示下一张图片',

    'showIndexBtn'          => '目录',
    'showIndexBtnTitle'         => '回到相簿目录',

    'showImageBtn'          => '新窗口显示图片',
    'showImageBtnTitle'         => '于新窗口内显示图片',

    'showHiResBtn'          => '原大小图片 (#size#)',
    'showHiResBtnTitle'         => '于新窗口内显示原有高分辨率的图片',

    'showShowDetailsBtn'        => '显示详细资料',
    'showShowDetailsBtnTitle'   => '显示图片的 EXIF 详细数据：图片日期，快门速度等等（如有）。',

    'showHideDetailsBtn'        => '隐藏详细资料',
    'showHideDetailsBtnTitle'   => '隐藏图片的 EXIF 详细数据',

    'showRotateBtn'         => '旋转',
    'showRotateBtnTitle'        => '把图片顺时针作９０度旋转',

    'showExifFilename'      => '文件名称：',
    'showExifFilesize'      => '档案大小：',
    'showExifResolution'        => '分辨率：',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => '日期：',
    'showExifCamera'            => '相机型号：',
    'showExifExposure'          => '曝光时间：',
    'showExifAperture'          => '光圈大小：',
    'showExifFocalLength'       => '焦距：',
    'showExifFlashYes'          => '有',
    'showExifFlashNo'           => '没有',
    'showExifFlash'             => '使用闪光灯：',
    'showExifDialogTitle'       => '图片详细数据',

    'showImageTitleImage'       => '请按此处以显示下一张图片: #image#',
    'showImageTitleIndex'       => '请按此处以回到相簿目录',


    // edit*.php
    'editTitle'         => '编辑 #filename#',
    'editDlgTitle'          => '相簿定义档案',
    'editFileLocation'      => '档案位置',

    'editEditAsTextBtn'     => '以纯文字编辑',
    'editEditAsTextBtnTitle'    => '以纯文字编辑此档案',
    'editReindexNote'       => '请注意：在更改图片的大小设定后，您必须重建索引。',

    'editAlbumTitle'            => '相簿名称：',
    'editAlbumDate'             => '日期：',
    'editAlbumComment'          => '备忘：',
    'editAlbumTitleImage'           => '封面图片：',
    'editAlbumDefault'          => '是否为预设相簿：',
    'editAlbumUsers'            => '容许观看的用户：',
    'editAlbumUsersNote'        => '(comma-separated user list, empty string or <B>all</B> = anonymous access, <B>valid-user</B>=any authenticated user)',

    'editCancelBtn'             => '取消',
    'editSaveBtn'               => '储存',

    'editThumbLink'             => '#filename# （在新窗口开启）',
    'editImgFilename'           => '文件名称<BR><small>（更改字符串＝更改文件名，删除字符串＝删除档案）</small>:',
    'editImgTitle'              => '名称：',
    'editImgComment'            => '备忘：',
    'editImgResize'             => '更改图片大小',
    'editNewFileMessage'            => '（新档案）',
    'editTop'               => '回到最上',

    'editRenameError'           => '无法将文件名称更改成 #filename# ，无效的扩展名',
    'editSaveError'             => '储存相簿定义档案 #filename# 时发生错误',
    'editHTML'                  => 'HTML',
    'editText'                  => '纯文字',

    // reindex.php
    'reindexTitle'              => 'DAlbum 重建索引',
    'reindexDlgTitle'           => 'DAlbum 重建索引',
    'reindexDlgComment'         => 'DAlbum 重建索引，系统正在数据夹找寻新的图片，建立遗漏的图片预览，并更新图片数据库。',
    'reindexDlgSpeed'           => '请选择重建索引的速度：',

    'reindexSpeed0'             => '<B>快</B>。只建立不存在的图片预览和缩小图片。不会检查图片的完整性。',
    'reindexSpeed1'             => '<B>一般</B>。只建立不存在或损坏的图片预览和缩小图片。检查图片的完整性。',
    'reindexSpeed2'             => '<B>慢</B>。与 <B>一般</B> 大致相同，但会删除已没有关连的图片预览和缩小的图片。',
    'reindexSpeed3'             => '<B>很慢</B>。重新建立图片预览和缩小图片。警告：可能需要几小时！',

    'reindexCancelBtn'          => '取消',
    'reindexStartBtn'           => '开始',

    'reindexProgressTitle'      => 'DAlbum 重建索引中…',

    'reindexError'              => '建立图片预览时发生错误',
    'reindexRetry'              => '重试错误的图片',
    'reindexIgnore'             => '忽略错误并继续',
    'reindexAgain'              => '重头开始重建索引',

    'reindexMainImageProblem'   => '图片问题',
    'reindexResizedProblem'     => '缩小图片问题',
    'reindexThumbProblem'       => '图片预览问题',

    'reindexCompleted'          => '<P>完成。</P><P>重建索引共使用了 #elapsed# 秒，并且用了 #treeelapsed# 秒来建相簿树状结构。</P>',
    'reindexStats'              => 'DAlbum 资料统计',
    'reindexStatsAlbums'        => '相簿数目：',
    'reindexStatsImages'        => '图片数目：',
    'reindexStatsOrigSize'      => '原图片总大小：',
    'reindexStatsResizedSize'   => '缩小图片总大小：',
    'reindexStatsThumbSize'     => '图片预览总大小：',

    'reindexStatusErrors'       => '<B>状态： </B> 共找到 #errors# 个错误：',

    'reindexStatusOK'           => '<B>状态：</B> 成功。没有发现任何错误。',
    'reindexSaveError'          => '<B>错误：</B> 无法储存 #filename#',

    'reindexTHFilename'         => '文件名称',
    'reindexTHProblem'          => '问题',

    ''  => ''
);

?>
