<?php

/*  DAlbum Chinese-Big5 language support file

    (c) Copyright 2003 by DeltaX Inc.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'      => '登入',
    'loginBtnTitle'     => '登入',

    'logoutBtn'         => '登出',
    'logoutBtnTitle'    => '登出',

    'reindexBtn'        => '重建索引',
    'reindexBtnTitle'   => '找尋新的圖片並更新至 DAlbum 資料庫',

    'usrmgrBtn'         => '用戶',
    'usrmgrBtnTitle'    => '新增／移除使用者，或改變密碼',

    'closeWindowBtn'    => '關閉全螢幕',
    'closeWindowBtnTitle'   => '關閉全螢幕',

    'fullScreenBtn'     => '全螢幕',
    'fullScreenBtnTitle'    => '以全螢幕開啟此頁，效果與按 F11 相同',

    'editDefBtn'        => '編輯',
    'editDefBtnTitle'   => '修改相簿名稱，備忘，以及管理相簿內的圖片。',

    'indexUsername'     => '用戶：',
    'page'          => '顯示第 #begin# - #end# 個項目，總共有 #count# 個項目。&nbsp;頁數：',
    'noimages'      => '沒有圖片',
    'noPublicImages'    => '沒有公開的圖片，請登入。',
    'noscript'      => '對不起，您的瀏覽器需要開啟 Javascript 的功能，才能顯示樹狀目錄。<BR><BR>請於瀏覽器選項開啟此功能。',

    'prevPageBtn'           => '&lt;&lt;',
    'prevPageBtnTitle'      => '#page#',

    'nextPageBtn'           => '&gt;&gt;',
    'nextPageBtnTitle'      => '(#page#)',

    'statusLeft'            => '共有 <b>#TotalImages#</b> 分別圖片存放於 <b>#TotalAlbums#</b> 個相簿',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'          => '回到主頁',
    'username'          => '用戶名稱：',
    'password'          => '密碼：',
    'bytes'             => '位元組',
    'KB'                => 'KB',
    'MB'                => 'MB',
    'pixels'            => '像素',
    'errorReturn'           => '回到上一頁',

    /// Login.php
    'loginTitle'            => '登入至 #title#',
    'loginAuthError'        => '認證錯誤',
    'loginBadUserName'      => '用戶名稱或密碼錯誤',
    'loginAgain'            => '重新登入',
    'loginNoCookiesWarning'     =>  '<HR><B>警告：您的瀏覽器已關掉 Cookies 功能！</B><BR>請於瀏覽器選項開啟 Cookies 功能，再重新整理此頁。<BR><HR>',
    'loginLoginBtn'         => '登入',
    'loginCancelBtn'        => '取消',

    // pass.php
    'passTitle'         => '用戶管理',
    'passUserExists'        => '#user# 已經存在',
    'passNotMatch'          => '密碼不正確',
    'passNoUserSelected'        => '沒有選擇用戶',
    'passNoAdminDelete'     => '不能刪除主要的 DAlbum 管理員！',
    'passWriteError'        => '無法寫入密碼檔！',
    'passError'             => '<B>錯誤：</B>#error#',
    'passAddBtn'            => '增加',
    'passDeleteBtn'         => '刪除',
    'passChangePwdBtn'      => '更改密碼',
    'passCloseBtn'          => '關閉',
    'passCancelBtn'         => '取消',

    'passAddUserDlgTitle'       => '增加用戶',
    'passChangePwdDlgTitle'     => '更改密碼',
    'passConfirmPassword'       => '確認密碼：',

    // showimg.php
    'showPrevBtn'           => '上一頁',
    'showPrevBtnTitle'      => '顯示上一張圖片',

    'showNextBtn'           => '下一頁',
    'showNextBtnTitle'      => '顯示下一張圖片',

    'showIndexBtn'          => '目錄',
    'showIndexBtnTitle'         => '回到相簿目錄',

    'showImageBtn'          => '新視窗顯示圖片',
    'showImageBtnTitle'         => '於新視窗內顯示圖片',

    'showHiResBtn'          => '原大小圖片 (#size#)',
    'showHiResBtnTitle'         => '於新視窗內顯示原有高解析度的圖片',

    'showShowDetailsBtn'        => '顯示詳細資料',
    'showShowDetailsBtnTitle'   => '顯示圖片的 EXIF 詳細資料：圖片日期，快門速度等等（如有）。',

    'showHideDetailsBtn'        => '隱藏詳細資料',
    'showHideDetailsBtnTitle'   => '隱藏圖片的 EXIF 詳細資料',

    'showRotateBtn'         => '旋轉',
    'showRotateBtnTitle'        => '把圖片順時針作９０度旋轉',

    'showExifFilename'      => '檔案名稱：',
    'showExifFilesize'      => '檔案大小：',
    'showExifResolution'        => '解析度：',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => '日期：',
    'showExifCamera'            => '相機型號：',
    'showExifExposure'          => '曝光時間：',
    'showExifAperture'          => '光圈大小：',
    'showExifFocalLength'       => '焦距：',
    'showExifFlashYes'          => '有',
    'showExifFlashNo'           => '沒有',
    'showExifFlash'             => '使用閃光燈：',
    'showExifDialogTitle'       => '圖片詳細資料',

    'showImageTitleImage'       => '請按此處以顯示下一張圖片: #image#',
    'showImageTitleIndex'       => '請按此處以回到相簿目錄',


    // edit*.php
    'editTitle'         => '編輯 #filename#',
    'editDlgTitle'          => '相簿定義檔案',
    'editFileLocation'      => '檔案位置',

    'editEditAsTextBtn'     => '以純文字編輯',
    'editEditAsTextBtnTitle'    => '以純文字編輯此檔案',
    'editReindexNote'       => '請注意：在更改圖片的大小設定後，您必須重建索引。',

    'editAlbumTitle'            => '相簿名稱：',
    'editAlbumDate'             => '日期：',
    'editAlbumComment'          => '備忘：',
    'editAlbumTitleImage'           => '封面圖片：',
    'editAlbumDefault'          => '是否為預設相簿：',
    'editAlbumUsers'            => '容許觀看的用戶：',
    'editAlbumUsersNote'        => '(comma-separated user list, empty string or <B>all</B> = anonymous access, <B>valid-user</B>=any authenticated user)',

    'editCancelBtn'             => '取消',
    'editSaveBtn'               => '儲存',

    'editThumbLink'             => '#filename# （在新視窗開啟）',
    'editImgFilename'           => '檔案名稱<BR><small>（更改字串＝更改檔名，刪除字串＝刪除檔案）</small>:',
    'editImgTitle'              => '名稱：',
    'editImgComment'            => '備忘：',
    'editImgResize'             => '更改圖片大小',
    'editNewFileMessage'            => '（新檔案）',
    'editTop'               => '回到最上',

    'editRenameError'           => '無法將檔案名稱更改成 #filename# ，無效的副檔名',
    'editSaveError'             => '儲存相簿定義檔案 #filename# 時發生錯誤',
    'editHTML'                  => 'HTML',
    'editText'                  => '純文字',

    // reindex.php
    'reindexTitle'              => 'DAlbum 重建索引',
    'reindexDlgTitle'           => 'DAlbum 重建索引',
    'reindexDlgComment'         => 'DAlbum 重建索引，系統正在資料夾找尋新的圖片，建立遺漏的圖片預覽，並更新圖片資料庫。',
    'reindexDlgSpeed'           => '請選擇重建索引的速度：',

    'reindexSpeed0'             => '<B>快</B>。只建立不存在的圖片預覽和縮小圖片。不會檢查圖片的完整性。',
    'reindexSpeed1'             => '<B>一般</B>。只建立不存在或損壞的圖片預覽和縮小圖片。檢查圖片的完整性。',
    'reindexSpeed2'             => '<B>慢</B>。與 <B>一般</B> 大致相同，但會刪除已沒有關連的圖片預覽和縮小的圖片。',
    'reindexSpeed3'             => '<B>很慢</B>。重新建立圖片預覽和縮小圖片。警告：可能需要幾小時！',

    'reindexCancelBtn'          => '取消',
    'reindexStartBtn'           => '開始',

    'reindexProgressTitle'      => 'DAlbum 重建索引中…',

    'reindexError'              => '建立圖片預覽時發生錯誤',
    'reindexRetry'              => '重試錯誤的圖片',
    'reindexIgnore'             => '忽略錯誤並繼續',
    'reindexAgain'              => '重頭開始重建索引',

    'reindexMainImageProblem'   => '圖片問題',
    'reindexResizedProblem'     => '縮小圖片問題',
    'reindexThumbProblem'       => '圖片預覽問題',

    'reindexCompleted'          => '<P>完成。</P><P>重建索引共使用了 #elapsed# 秒，並且用了 #treeelapsed# 秒來建相簿樹狀結構。</P>',
    'reindexStats'              => 'DAlbum 資料統計',
    'reindexStatsAlbums'        => '相簿數目：',
    'reindexStatsImages'        => '圖片數目：',
    'reindexStatsOrigSize'      => '原圖片總大小：',
    'reindexStatsResizedSize'   => '縮小圖片總大小：',
    'reindexStatsThumbSize'     => '圖片預覽總大小：',

    'reindexStatusErrors'       => '<B>狀態： </B> 共找到 #errors# 個錯誤：',

    'reindexStatusOK'           => '<B>狀態：</B> 成功。沒有發現任何錯誤。',
    'reindexSaveError'          => '<B>錯誤：</B> 無法儲存 #filename#',

    'reindexTHFilename'         => '檔案名稱',
    'reindexTHProblem'          => '問題',

    ''  => ''
);

?>